global:
  scrape_interval: 15s  # Как часто собирать метрики

scrape_configs:
  - job_name: 'prometheus'  # Мониторим сам Prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mysql-master'  # Мониторим MySQL на Master
    static_configs:
      - targets: ['localhost:9104']  # Используем mysqld_exporter (поясню ниже)

  - job_name: 'node-exporter'  # Мониторим сервер (CPU, RAM, Disk)
    static_configs:
      - targets: ['localhost:9100']
